name: Windows
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: [ trunk ]
    paths:
    - '**'
    - '!**.yml'
    - '!**.md'
    - '**/windows.yml'

  pull_request:
    branches: [ trunk ]
    paths:
    - '**'
    - '!**.yml'
    - '!**.md'
    - '**/windows.yml'

jobs:
  msvc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install Meson and Ninja
      run: pip install meson ninja

    - name: Meson setup
      env:
        PKG_CONFIG_PATH: ${{ env.VCPKG_INSTALLATION_ROOT }}\installed\x64-windows\lib\pkgconfig
      run: |
        meson setup _build -Db_sanitize=none -Dc_args="/WX"

    - name: Build
      run: meson compile -C _build

    - name: Test
      run: meson test --no-stdsplit -v -C _build
  MSYS2:
    runs-on: windows-latest
    needs: msvc
    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        install: >-
          git
        pacboy: >-
          gcc:p
          ninja:p
          meson:p
        update: true

    #- name: Install dependencies
      #shell: msys2 {0}
      #run: |
        #pacman --noconfirm --needed -S \
          #mingw-w64-x86_64-meson \
          #mingw-w64-x86_64-protobuf-c \
          #mingw-w64-x86_64-SDL2 \
          #mingw-w64-x86_64-SDL2_net \
          #mingw-w64-x86_64-SDL2_ttf

    - name: Meson setup
      shell: msys2 {0}
      run: |
        meson setup _build -Db_sanitize=none

    - name: Build
      shell: msys2 {0}
      run: |
        meson compile -C _build

    - name: Test
      shell: msys2 {0}
      run: |
        meson test -v -C _build
